# --------Build Stage--------
FROM node:22-slim AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install --force

COPY . .

RUN npm run build

# --------Production Stage--------
FROM nginx:1-alpine AS production

COPY --from=builder /app/dist /usr/share/nginx/html

COPY ./nginx/prod.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
