services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    ports:
      - "80:80"
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:latest
    container_name: FEEDIO_POSTGRES_PROD
    env_file:
      - .env
    volumes:
      - FEEDIO_POSTGRES_DATA:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: FEEDIO_PGADMIN_PROD
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "5050:80"
    restart: unless-stopped

volumes:
  FEEDIO_POSTGRES_DATA:

