### GET all dogs: http://localhost:5000/api/dog
GET http://localhost:5000/api/dog

###GET dog by id: http://localhost:5000/api/dog/:id
GET http://localhost:5000/api/dog/7a44a1dc-f411-4463-a72e-5f9de74e90b3

###Create a new dog: http://localhost:5000/api/dog
POST http://localhost:5000/api/dog
Content-Type: application/json

{
  "Name": "Momo",
  "Breed": "Poodle",
  "Weight": 14,
  "Disease": "Obesity",
  "Age": 8,
  "Sex": "Male"
}


###UPDATE dog by id: http://localhost:5000/api/dog/:id
PUT http://localhost:5000/api/dog/4371c1f5-91f8-4a95-897a-0697f7c4fdbb
Content-Type: application/json

{
  "Name": "Momo",
  "Breed": "Poodle",
  "Weight": 15,
  "Disease": "Obesity",
  "Age": 8,
  "Sex": "Male"
}

###DELETE dog by id: http://localhost:5000/api/dog/:id
DELETE http://localhost:5000/api/dog/7a44a1dc-f411-4463-a72e-5f9de74e90b3

