### GET all dogs: http://localhost:5000/api/dog
GET http://localhost:5000/api/dog

###GET dog by id: http://localhost:5000/api/dog/:id
GET http://localhost:5000/api/dog/eb5929e8-b73a-45d9-b88f-8bed308d1547

###Create a new dog: http://localhost:5000/api/dog
POST http://localhost:5000/api/dog
Content-Type: application/json

{
  "Name": "Momo",
  "Breed": "Poodle",
  "Weight": 14,
  "Disease": "Obesity",
  "Age": 8,
  "Sex": "Male"
}


###UPDATE dog by id: http://localhost:5000/api/dog/:id
PUT http://localhost:5000/api/dog/b3a8c781-4281-4140-88f3-ac3dc0f73285
Content-Type: application/json

{
  "Name": "Momo",
  "Breed": "Poodle",
  "Weight": 7,
  "Disease": "Obesity",
  "Age": 3,
  "Sex": "Male"
}

###DELETE dog by id: http://localhost:5000/api/dog/:id
DELETE http://localhost:5000/api/dog/eb5929e8-b73a-45d9-b88f-8bed308d1547

