### GET all dogs: http://localhost:5000/api/dog
GET http://localhost:5000/api/dog

###GET dog by id: http://localhost:5000/api/dog/:id
GET http://localhost:5000/api/dog/14251955-9c27-451a-b76e-3f05efff8bf6

###Create a new dog: http://localhost:5000/api/dog
POST http://localhost:5000/api/dog
Content-Type: application/json

{
  "name": "Momo",
  "breed": "Poodle",
  "weight": 14,
  "disease": "Obesity",
  "age": 8,
  "sex": "Male"
}


###UPDATE dog by id: http://localhost:5000/api/dog/:id
PUT http://localhost:5000/api/dog/eb63bfff-ec8e-4c0d-b692-3ef7792967f0
Content-Type: application/json

{
  "name": "Momo",
  "breed": "Poodle",
  "weight": 7,
  "disease": "Obesity",
  "age": 3,
  "sex": "Male"
}

###DELETE dog by id: http://localhost:5000/api/dog/:id
DELETE http://localhost:5000/api/dog/e41a454f-bad4-4755-91b1-27b723f6f0e3

